services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: itireland
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  itireland:
    container_name: itireland
    build: ./
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
    ports:
      - "8080:80"
  nginx:
    image: nginx
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"  # 添加443端口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/ec2-user/ITIreland/ssl:/etc/nginx/ssl  # 将SSL证书和私钥文件添加为卷
    depends_on:
      - itireland

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres: