services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: itireland
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  itireland:
    container_name: ITIreland
    build: ./
    networks:
      - spring
      - postgres

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: