spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/itireland?currentSchema=public
    username: postgres
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    jackson:
      time-zone: Europe/Dublin
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api
  error:
    include-message: always # Return Customized Exception Message to Client

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"


aws:
  region: eu-west-1
  s3:
    mock: false
    buckets:
      image: bucketeer-ffab8d38-4137-4522-a16c-881871c8e426



itireland:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://itireland.herokuapp.com