spring:
  config:
#    import: optional:file:.env[.yaml] # root path
    import: optional:classpath:.env[.yaml] # resources path
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/itireland?currentSchema=public
    username: postgres
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    jackson:
      time-zone: Europe/Dublin
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  codec:
    max-in-memory-size: 5MB

server:
  servlet:
    context-path: /api
  error:
    include-message: always # Return Customized Exception Message to Client

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"


aws:
  region: ${BUCKETEER_AWS_REGION}
  accessKeyId: ${BUCKETEER_AWS_ACCESS_KEY_ID}
  secretAccessKey: ${BUCKETEER_AWS_SECRET_ACCESS_KEY}
  s3:
    mock: false
    buckets:
      image: ${BUCKETEER_BUCKET_NAME}



itireland:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://itireland.herokuapp.com

